repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.2.1"  # Check the latest version on GitHub
    hooks:
      - id: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports"]

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"  # Check the latest version on GitHub
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/psf/black
    rev: "24.3.0"  # Check the latest version on GitHub
    hooks:
      - id: black
        args: ["--line-length=88"]